### ISSUE TITLE
Encountered Makefile.compiler: No such file or directory

### ISSUE THREAD

**Issue by mingfeng777** [WangNan0/kbuild-standalone#2]
I followed the instructions of the README to
> make -C ../ -f Makefile.sample O=`pwd` -j

But, I got an error.
> make -f .source/scripts/Makefile.build obj=fixdep  \
> 
> .source/scripts/Makefile.build:39: .source/scripts/Makefile.compiler: No such file or directory
> make[2]: *** No rule to make target '.source/scripts/Makefile.compiler'.  Stop.

I'm not sure I should add '-' before  'include $(srctree)/scripts/Makefile.compiler' at line 39 on kbuild/scripts/Makefile.build or copy Makefile.compiler file from linux.

If I copy Makefile.compiler file from linux, Makefile.am file I did not know if it is affected.

**Comment by WangNan0** [comment]
I have sync Makefile.compiler with Linux.

Please totally remove existing installation and check again:
`sudo rm /usr/local/lib/pkgconfig/kbuild-standalone.pc`
`sudo rm /usr/local/share/kbuild-standalone/`

**Comment by mingfeng777** [comment]
Thanks!
